[2025-03-25T04:07:52.222+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-25T04:07:52.376+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_to_postgresql_2.extract_attendance_data manual__2025-03-25T04:07:44.340446+00:00 [queued]>
[2025-03-25T04:07:52.421+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_to_postgresql_2.extract_attendance_data manual__2025-03-25T04:07:44.340446+00:00 [queued]>
[2025-03-25T04:07:52.433+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 3
[2025-03-25T04:07:52.546+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): extract_attendance_data> on 2025-03-25 04:07:44.340446+00:00
[2025-03-25T04:07:52.597+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=11170) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-25T04:07:52.600+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'api_to_postgresql_2', 'extract_attendance_data', 'manual__2025-03-25T04:07:44.340446+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/api_to_pgdatabase.py', '--cfg-path', '/tmp/tmppyujx_n9']
[2025-03-25T04:07:52.602+0000] {standard_task_runner.py:72} INFO - Started process 11253 to run task
[2025-03-25T04:07:52.602+0000] {standard_task_runner.py:105} INFO - Job 8: Subtask extract_attendance_data
[2025-03-25T04:07:53.067+0000] {task_command.py:467} INFO - Running <TaskInstance: api_to_postgresql_2.extract_attendance_data manual__2025-03-25T04:07:44.340446+00:00 [running]> on host a2397d360478
[2025-03-25T04:07:53.839+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='api_to_postgresql_2' AIRFLOW_CTX_TASK_ID='extract_attendance_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-25T04:07:44.340446+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-25T04:07:44.340446+00:00'
[2025-03-25T04:07:53.842+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-25T04:07:53.847+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-25T04:07:53.848+0000] {logging_mixin.py:190} INFO - Current task name:extract_attendance_data state:running start_date:2025-03-25 04:07:52.378488+00:00
[2025-03-25T04:07:53.850+0000] {logging_mixin.py:190} INFO - Dag name:api_to_postgresql_2 and current dag run status:running
[2025-03-25T04:07:53.851+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-25T04:07:53.883+0000] {base.py:84} INFO - Retrieving connection 'attendance_api'
[2025-03-25T04:09:17.802+0000] {http.py:204} ERROR - HTTP error: Bad Request
[2025-03-25T04:09:17.803+0000] {http.py:205} ERROR - {"Message":"Something went wrong. Please try again"}
[2025-03-25T04:09:17.817+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/hooks/http.py", line 202, in check_response
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://lucid.nassa.com.bd/api/Attendance/GetEmployeeAttendanceTodayv2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/api_to_pgdatabase.py", line 48, in extract_attendance_data
    response=http_hook.run(endpoint)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/hooks/http.py", line 191, in run
    return self.run_and_check(session, prepped_request, extra_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/hooks/http.py", line 244, in run_and_check
    self.check_response(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/hooks/http.py", line 206, in check_response
    raise AirflowException(str(response.status_code) + ":" + response.reason)
airflow.exceptions.AirflowException: 400:Bad Request
[2025-03-25T04:09:17.842+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-25T04:09:17.843+0000] {logging_mixin.py:190} INFO - Task start:2025-03-25 04:07:52.378488+00:00 end:2025-03-25 04:09:17.842132+00:00 duration:85.463644
[2025-03-25T04:09:17.843+0000] {logging_mixin.py:190} INFO - Task:<Task(_PythonDecoratedOperator): extract_attendance_data> dag:<DAG: api_to_postgresql_2> dagrun:<DagRun api_to_postgresql_2 @ 2025-03-25 04:07:44.340446+00:00: manual__2025-03-25T04:07:44.340446+00:00, state:running, queued_at: 2025-03-25 04:07:44.463853+00:00. externally triggered: True>
[2025-03-25T04:09:17.844+0000] {logging_mixin.py:190} INFO - Failure caused by 400:Bad Request
[2025-03-25T04:09:17.844+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=api_to_postgresql_2, task_id=extract_attendance_data, run_id=manual__2025-03-25T04:07:44.340446+00:00, execution_date=20250325T040744, start_date=20250325T040752, end_date=20250325T040917
[2025-03-25T04:09:17.869+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-25T04:09:17.871+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 8 for task extract_attendance_data (400:Bad Request; 11253)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/hooks/http.py", line 202, in check_response
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://lucid.nassa.com.bd/api/Attendance/GetEmployeeAttendanceTodayv2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/api_to_pgdatabase.py", line 48, in extract_attendance_data
    response=http_hook.run(endpoint)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/hooks/http.py", line 191, in run
    return self.run_and_check(session, prepped_request, extra_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/hooks/http.py", line 244, in run_and_check
    self.check_response(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/hooks/http.py", line 206, in check_response
    raise AirflowException(str(response.status_code) + ":" + response.reason)
airflow.exceptions.AirflowException: 400:Bad Request
[2025-03-25T04:09:17.924+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-25T04:09:17.959+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-25T04:09:17.962+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
